# Generated by Django 3.1.7 on 2021-04-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
