# Generated by Django 3.1.7 on 2021-04-08 21:29

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210407_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='lng',
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
